language: python

python:
  - "3.6.4"

before_install:
  - mv travis_secrets.yaml secrets.yaml
  - mv travis_zones.yaml zones.yaml

install:
  - pip3 install homeassistant

script:
  - hass -c . --script check_config
