homeassistant:
  # Name of the location where Home Assistant is running
  name: Casa
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome
  # Customization file
  customize: !include customize.yaml
  # Packages!
  packages: !include_dir_named packages
  # Auth Providers
  auth_providers:
    - type: homeassistant

zone:
group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
shell_command: !include shell_commands.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
input_boolean: !include input_booleans.yaml
input_text: !include input_texts.yaml
homekit: !include homekit.yaml
alert: !include alerts.yaml
#alarm_control_panel: !include alarm_control_panel.yaml
light: !include lights.yaml
history: !include history_filters.yaml

garbage_collection: !include garbage_collection.yaml

# # Custom Component https://github.com/rogro82/hass-variables
# variable: !include variables.yaml

# Enables the frontend
frontend:
# Aggiungi i Temi
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  #ssl_certificate: !secret ssl_certificate
  #ssl_key: !secret ssl_key
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  #base_url: !secret base_url
  #use_x_forwarded_for: true
  #trusted_proxies:
  #  - 192.168.1.1
  #ip_ban_enabled: true
  #login_attempts_threshold: 5

# Discover some devices automatically
discovery:
  # ignore:
  #   - google_cast

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Tracked history is kept for 2 days
recorder:
  #purge_keep_days: 2
  db_url: !secret db_url

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
#map:

# Track the sun
sun:

# Cloud
cloud: !include cloud.yaml

#iPhones
ios:
  push:
    categories:
      - name: Allarme
        identifier: 'allarme'
        actions:
          - identifier: 'ALLARME_ON'
            title: 'Allarme ON'
            activationMode: 'background'
            authenticationRequired: true
            destructive: false
            behavior: 'default'
          - identifier: 'ALLARME_OFF'
            title: 'Allarme OFF'
            activationMode: 'background'
            authenticationRequired: true
            destructive: true
            behavior: 'default'

mobile_app:

# logger:
#   default: info
#   logs:
#     pydeconz: debug
#     homeassistant.components.deconz: debug

# Default Config
default_config:

# System Health
system_health:

###############################################################################

# coinbase:
#   api_key: !secret coinbase_key
#   api_secret: !secret coinbase_key_secret
#   exchange_rate_currencies:
#     - BTC
#     - BCH
#     - ETH
#     - LTC

yeelight:
  devices:
    192.168.1.38:
      name: Plafoniera

media_player:
 - platform: yamaha
   source_names:
     HDMI1: "Blu-Ray"
     HDMI2: "MacBook"
     HDMI3: "Xbox360"
     HDMI4: "Fire TV"
     AV5: "Cassette"
     AV6: "TV"

webostv:
  host: !secret lg_ip
  name: TV Salotto

ifttt:
  key: !secret ifttt_key

# owntracks:
#   max_gps_accuracy: 100

mqtt:
  discovery: true
  broker: !secret hassio_interno_ip
  username: !secret mqtt_username
  password: !secret mqtt_password

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: homeassistant
  max_retries: 3
  default_measurement: state

# weather:
#  - platform: darksky
#    api_key: !secret darksky_key

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_alby_chat_id
      - !secret telegram_ale_chat_id
      - !secret telegram_ma_chat_id
      - !secret telegram_pa_chat_id

notify:
  # - name: telefoni
  #   platform: group
  #   services:
  #     - service: mobile_app_iphone_di_alby
  #     - service: mobile_app_iphone_di_alessandra
  - name: telegram
    platform: group
    services:
      - service: telegram_alby
      - service: telegram_ale
      - service: telegram_ma
      - service: telegram_pa
  - name: telegram_alby
    platform: telegram
    chat_id: !secret telegram_alby_chat_id
  - name: telegram_ale
    platform: telegram
    chat_id: !secret telegram_ale_chat_id
  - name: telegram_ma
    platform: telegram
    chat_id: !secret telegram_ma_chat_id
  - name: telegram_pa
    platform: telegram
    chat_id: !secret telegram_pa_chat_id
  - platform: tts
    name: in_salotto
    tts_service: tts.cloud_say
    media_player: media_player.salotto
    language: it-IT
  - platform: tts
    name: in_camera
    tts_service: tts.cloud_say
    media_player: media_player.camera_da_letto
    language: it-IT
  - platform: tts
    name: in_cucina
    tts_service: tts.cloud_say
    media_player: media_player.cucina
    language: it-IT
  # - name: firetv
  #   platform: nfandroidtv
  #   host: !secret firetv_ip
  #   fontsize: max
  #   duration: 10
  #   position: top-right
  # - platform: webostv
  #   host: !secret lg_ip
  #   name: tv_salotto

stream:

camera:
  - platform: foscam
    ip: !secret foscam_c2_ip
    username: !secret foscam_username
    password: !secret foscam_password
    name: C2
  - platform: generic
    name: cucina
    still_image_url: !secret CameraCucina_URL
    stream_source: !secret CameraCucina_Source
  - platform: generic
    name: fianco
    still_image_url: !secret CameraFianco_URL
    stream_source: !secret CameraFianco_Source
  - platform: generic
    name: retro
    still_image_url: !secret CameraRetro_URL
    stream_source: !secret CameraRetro_Source
  - platform: generic
    name: garage
    still_image_url: !secret CameraGarage_URL
    stream_source: !secret CameraGarage_Source

#Proximity
proximity:
  home:
    ignored_zones:
      - lavoro
      - ufficio
    devices:
      - device_tracker.iphone_di_alby
      - device_tracker.iphone_di_alessandra

#tplink:
#  switch:
#    - host: !secret tplink_switch_ip

#climate:
#  - platform: netatmo

pi_hole:
  host: !secret pi_hole_host

cover:
  - platform: template
    covers:
      tenda_cucina:
        device_class: shutter
        friendly_name: "Tenda Cucina"
        open_cover:
          service: script.apri_tenda_cucina
        close_cover:
          service: script.chiudi_tenda_cucina
        stop_cover:
          service: script.stop_tenda_cucina