homeassistant:
  # Name of the location where Home Assistant is running
  name: Via Rossetti
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome
  # Customization file
  customize: !include customize.yaml

  customize_glob: !include customize_glob.yaml


zone: !include zones.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
shell_command: !include shell_commands.yaml

customizer:
  custom_ui: hosted

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# Tracked history is kept for 10 days
recorder:
  purge_keep_days: 10

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor: !include sensors.yaml

variable:
  ultimo_movimento:
    value: 'Unknown'
    restore: true
    attributes:
      icon: mdi:map-marker
      name: "Ultimo Movimento"

# Text to speech
tts:
  - platform: google
    language: 'it'

# Cloud
cloud:

#iPhones
ios:

#Shopping List
#shopping_list:

switch: !include switches.yaml

light:
  - platform: hue
    host: 192.168.2.5

panel_iframe:
  configurator:
    title: Configuratore
    icon: mdi:wrench
    url: !secret configurator_url
  nodered:
    title: Node-RED
    icon: mdi:nodejs
    url: !secret nodered_url

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_key

media_player:
  - platform: yamaha
    source_names:
      HDMI1: "Blu-Ray"
      HDMI2: "MacBook"
      HDMI3: "Xbox360"
      HDMI4: "Fire TV"
      AV5: "Cassette"
      AV6: "TV"
  - platform: firetv
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

neato:
  username: !secret neato_username
  password: !secret neato_password

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.2.9-10

#weather:
#  - platform: darksky
#    api_key: !secret darksky_key

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

ifttt:
  key: !secret ifttt_key

notify:
  - name: telefoni
    platform: group
    services:
      - service: ios_iphone_di_alby
      - service: ios_iphone_di_alessandra
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat_id

camera:
  - platform: foscam
    ip: 192.168.2.24
    username: !secret foscam_username
    password: !secret foscam_password
    name: Occhio

input_datetime:
  alba:
    name: Orario
    has_date: false
    has_time: true
    initial: 06:45
input_boolean:
  alarmweekday:
    name: Giorni Lavorativi
    initial: on
    icon: mdi:calendar
  alarmweekon:
    name: Attivato
    initial: on
    icon: mdi:power
input_number:
  spotify_volume:
    name: Volume
    icon: mdi:volume-high
    min: 0.3
    max: 0.6
    step: 0.01
    initial: 0.45
input_select:
  spotify_playlist:
    name: 'Playlist:'
    options:
      - Rossetti
      - Balbertandra
      - Discover Weekly Alby
#      - Discover Weekly Ale
      - Infinite Indie Folk
      - Gemme Sparse
      - Massima Concentrazione
      - Le Hit del Natale
    initial: Rossetti
    icon: mdi:spotify
  spotify_source:
    name: 'Source:'
    options:
      - Yamaha Salotto
      - Amazon FireTV
    initial: Yamaha Salotto
    icon: mdi:speaker-wireless
