title: Casa
views:
  - badges:
      - device_tracker.alby_iphone
      - device_tracker.alessandra_iphone
      - binary_sensor.clio
      - binary_sensor.swift
      - binary_sensor.papera
    cards:
      - cards:
          - entities:
              - sensor.fasilunari
              - sensor.lavorocasa_ale
              - sensor.lavorocasa_alby
              - sensor.giornialnatale
            show_header_toggle: false
            title: Sensori
            type: entities
          - entities:
              - binary_sensor.presence_3
              - binary_sensor.presence_5
              - binary_sensor.presence_6
              - binary_sensor.presence_4
            type: entities
          - entities:
              - binary_sensor.openclose_13
              - binary_sensor.finestra_bagno
              - binary_sensor.portafinestra_salotto_dx
              - binary_sensor.openclose_8
              - binary_sensor.openclose_9
              - binary_sensor.openclose_15
              - binary_sensor.openclose_14
              - binary_sensor.portafinestra_camera
            type: entities
        type: vertical-stack
      - aspect_ratio: 100%
        entities:
          - entity: device_tracker.alby_iphone
          - entity: device_tracker.alessandra_iphone
          - zone.home
        id: 8805229942194e25a959b1617d22694e
        title: Famiglia
        type: map
      - entities:
          - input_boolean.alarmweekon
          - input_datetime.alba
          - input_boolean.alarmweekday
        id: e68b032ec8964181859f5699c28c48f7
        show_header_toggle: false
        title: Alba in 5 minuti
        type: entities
      - camera_image: camera.semola_cleaning_map
        entities:
          - vacuum.semola
        id: 30226c06b6174672a4ee4d3b05db5508
        title: Semola
        type: picture-glance
      - entities:
          - input_select.scelta_vettura
          - input_select.scelta_persona
          - input_boolean.controllo
        id: 6d021c6500d1438382317138298b8292
        show_header_toggle: false
        title: Notifica Macchina
        type: entities
      - entities:
          - switch.nuvola
          - input_datetime.durata_timer
          - input_boolean.timer
        id: bb2b379b713b41c2b035921a9b364190
        show_header_toggle: false
        title: Timer Nuvola
        type: entities
      - entity: media_player.cucina
        type: media-control
      - entities:
          - input_boolean.corsa
          - switch.natalino
        show_header_toggle: false
        title: Utilità
        type: entities
      - entity: media_player.yamaha_receiver
        id: c0620cb1b34e44ad9f45f2789db63c9e
        type: media-control
    id: principale
    title: Principale
  - cards:
      - cards:
          - camera_image: camera.cucina
            entities:
              - sensor.temperature_10
              - sensor.humidity_11
              - sensor.pressure_12
            title: Cucina
            type: picture-glance
          - entities:
              - light.cucina_2
              - binary_sensor.fire_28
            show_header_toggle: false
            type: entities
        type: vertical-stack
      - entities:
          - scene.caldo
          - scene.netflix
          - entity: light.divano_2
            secondary_info: last-changed
          - entity: light.tv_2
            secondary_info: last-changed
        show_header_toggle: false
        title: Salotto
        type: entities
      - entities:
          - scene.entrata
          - entity: light.disimpegno_2
            secondary_info: last-changed
        show_header_toggle: false
        title: Disimpegno
        type: entities
      - entities:
          - binary_sensor.water_sensor
        title: Bagno
        type: entities
        show_header_toggle: false
      - entities:
          - scene.nanna
          - entity: light.camera
            secondary_info: last-changed
          - entity: light.plafoniera
            secondary_info: last-changed
        id: eae5d8f98aa846d7923b9cbc74aea32f
        show_header_toggle: false
        title: Camera
        type: entities
    id: stanze
    title: Stanze
  - cards:
      - cards:
          - aspect_ratio: 100%
            type: iframe
            url: >-
              https://embed.windy.com/embed2.html?lat=44.606&lon=7.383&zoom=6&level=surface&overlay=rain&menu=&message=true&marker=&calendar=true&type=map&location=coordinates&detail=&detailLat=45.050&detailLon=7.667&metricWind=km%2Fh&metricTemp=%C2%B0C&radarRange=-1
          - entities:
              - variable.meteo
              - sensor.dark_sky_apparent_temperature
              - sensor.dark_sky_cloud_coverage
              - sensor.dark_sky_wind_speed
              - sensor.dark_sky_cloud_coverage_1
              - sensor.dark_sky_wind_speed_1
            type: entities
        id: 9e6f09afa6af4b34b4e55de576b877ca
        type: vertical-stack
    id: meteo
    title: Meteo
  - cards:
      - entities:
          - group.all_automations
        show_header_toggle: false
        title: Automazioni
        type: entities
      - entities:
          - sensor.mese
          - sensor.turno
        show_header_toggle: false
        title: Cena del 15
        type: entities
      - entities:
          - sensor.speedtest_download
          - sensor.speedtest_ping
          - sensor.speedtest_upload
        show_header_toggle: false
        title: Speedtest
        type: entities
      - entities:
          - sensor.saldo_eth
          - sensor.coinbase_eth_wallet
          - sensor.coinbase_eur_wallet
          - sensor.saldo_mining
        show_header_toggle: false
        title: Criptovalute
        type: entities
      - entities:
          - sensor.tp_link_amps
          - sensor.tp_link_watts
          - sensor.tp_link_kw
          - sensor.tp_link_kw_today
          - sensor.tp_link_volts
        show_header_toggle: false
        title: Smart Plug
        type: entities
      - entities:
          - sensor.nut_ups_status_data
          - sensor.nut_ups_input_voltage
          - sensor.nut_ups_load
          - sensor.nut_ups_battery_runtime
          - sensor.nut_ups_battery_charge
        show_header_toggle: false
        title: UPS
        type: entities
    id: cofano
    title: Cofano
  - cards:
      - entities:
          - sensor.tempo_online
          - sensor.disk_use_percent_home
          - sensor.memory_free
        show_header_toggle: false
        title: Sistema
        type: entities
      - entities:
          - switch.hadockermon_transmissionopenvpnproxy
          - switch.hadockermon_addon_a0d7b954_grafana
          - switch.hadockermon_addon_a0d7b954_influxdb
          - switch.hadockermon_addon_03d23610_dasshio
          - switch.hadockermon_addon_core_configurator
          - switch.hadockermon_addon_core_samba
          - switch.hadockermon_syncthing
          - switch.hadockermon_watchtower
        show_header_toggle: false
        title: Containers
        type: entities
    id: nuc
    title: NUC