homeassistant:
############ DATA E ORA ########################################################
input_datetime:
  alba:
    name: Orario
    has_date: false
    has_time: true
    initial: 07:27
############ LAVORATIVO ########################################################
binary_sensor:
  - platform: workday
    country: IT
############ BOOLEANI ##########################################################
input_boolean:
  alarmweekday:
    name: Giorni Lavorativi
    initial: on
    icon: mdi:calendar
  alarmweekon:
    name: Attivato
    #initial: on
    icon: mdi:power
############ AUTOMAZIONI #######################################################
automation:
  - alias: Buongiorno Lavorativo
    initial_state: True
    trigger:
      platform: time_pattern
      minutes: '/1'
      seconds: 0
    condition:
      - condition: state
        entity_id: input_boolean.alarmweekon
        state: 'on'
      - condition: state
        entity_id: input_boolean.alarmweekday
        state: 'on'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
      - condition: template
        value_template: '{{ now().strftime("%H:%M:00") == states.input_datetime.alba.state }}'
    action:
      - service: light.turn_on
        data:
          entity_id: light.camera
          transition: 180
          brightness: 104
          xy_color: [0.385, 0.384]

  - alias: Buongiorno Festivo
    initial_state: True
    trigger:
      platform: time_pattern
      minutes: '/1'
      seconds: 0
    condition:
      - condition: state
        entity_id: input_boolean.alarmweekon
        state: 'on'
      - condition: state
        entity_id: input_boolean.alarmweekday
        state: 'off'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'off'
      - condition: template
        value_template: '{{ now().strftime("%H:%M:00") == states.input_datetime.alba.state }}'
    action:
      - service: light.turn_on
        data:
          entity_id: light.camera
          transition: 180
          brightness: 104
          xy_color: [0.385, 0.384]
############ GRUPPO ############################################################
# group:
#   alarmclock:
#     name: Alba in 5 minuti
#     control: hidden
#     icon: mdi:weather-sunset
#     entities:
#       - input_boolean.alarmweekon
#       - input_datetime.alba
#       - input_boolean.alarmweekday
################################################################################
