homeassistant:
############ SENSORE ##########################################################
sensor:
  # sensore preso da https://www.home-assistant.io/components/sensor.version/
  # vedere anche https://community.home-assistant.io/t/sensor-for-latest-docker-image-versions/48745
  - platform: version
    name: Versione Hassio Locale
    source: local
  - platform: version
    name: Ultima Versione Hassio 
    source: hassio
############ AUTOMAZIONI ######################################################
automation:
  - alias: Notifica aggiornamento
    trigger:
    - platform: state
      entity_id: sensor.ultima_versione_hassio
    condition:
      - condition: template
        value_template: "{{ states.sensor.versione_hassio_locale.state != states.sensor.ultima_versione_hassio.state }}"
    action:
      - service: notify.ios_iphone_di_alby
        data_template:
          message: 'È disponibile Home Assistant {{ states.sensor.ultima_versione_hassio.state }}.'
      - service: persistent_notification.create
        data_template:
          notification_id: update_ha
          title: Aggiornamento
          message: >
            È disponibile Home Assistant {{ states.sensor.ultima_versione_hassio.state }}.
###############################################################################